CREATE TABLE IF NOT EXISTS `asset_change_record` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `change_code` varchar(64) NOT NULL COMMENT '变更单号',
  `asset_id` int NOT NULL COMMENT '资产ID',
  `asset_code` varchar(64) DEFAULT NULL COMMENT '资产编码',
  `asset_name` varchar(128) DEFAULT NULL COMMENT '资产名称',
  `change_type` varchar(32) NOT NULL COMMENT '变更类型',
  `old_value` varchar(255) DEFAULT NULL COMMENT '原值',
  `new_value` varchar(255) DEFAULT NULL COMMENT '新值',
  `change_reason` varchar(500) NOT NULL COMMENT '变更原因',
  `change_date` datetime DEFAULT NULL COMMENT '计划变更日期',
  `applicant_id` int DEFAULT NULL COMMENT '申请人ID',
  `applicant_name` varchar(64) DEFAULT NULL COMMENT '申请人',
  `apply_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '申请时间',
  `audit_status` int NOT NULL DEFAULT '1' COMMENT '审核状态 1待审核 2已通过 3已驳回 4已撤销',
  `auditor_id` int DEFAULT NULL COMMENT '审核人ID',
  `auditor_name` varchar(64) DEFAULT NULL COMMENT '审核人',
  `audit_date` datetime DEFAULT NULL COMMENT '审核时间',
  `audit_remark` varchar(500) DEFAULT NULL COMMENT '审核意见',
  `execute_status` int NOT NULL DEFAULT '0' COMMENT '执行状态 0未执行 1处理中 2已完成',
  `executor_name` varchar(64) DEFAULT NULL COMMENT '执行人',
  `execute_date` datetime DEFAULT NULL COMMENT '执行时间',
  `scrap_value` varchar(32) DEFAULT NULL COMMENT '报废净值/残值',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `delete_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记 0正常 1删除',
  PRIMARY KEY (`id`),
  KEY `idx_asset_change_asset` (`asset_id`),
  KEY `idx_asset_change_type` (`change_type`),
  KEY `idx_asset_change_status` (`audit_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产报废及变更记录';

CREATE TABLE IF NOT EXISTS `asset_warning_record` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `asset_id` int NOT NULL COMMENT '资产ID',
  `asset_code` varchar(64) DEFAULT NULL COMMENT '资产编码',
  `asset_name` varchar(128) DEFAULT NULL COMMENT '资产名称',
  `warning_type` varchar(64) NOT NULL COMMENT '预警类型',
  `warning_level` varchar(16) DEFAULT NULL COMMENT '预警级别',
  `warning_date` datetime DEFAULT NULL COMMENT '预警日期',
  `due_date` datetime DEFAULT NULL COMMENT '到期日期',
  `days_left` int DEFAULT NULL COMMENT '剩余天数',
  `status` int NOT NULL DEFAULT '1' COMMENT '处理状态 1待处理 2处理中 3已完成',
  `description` varchar(500) DEFAULT NULL COMMENT '预警描述',
  `action_required` varchar(500) DEFAULT NULL COMMENT '建议措施',
  `handler_id` int DEFAULT NULL COMMENT '处理人ID',
  `handler_name` varchar(64) DEFAULT NULL COMMENT '处理人',
  `handle_time` datetime DEFAULT NULL COMMENT '处理时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_asset_warning` (`asset_id`,`warning_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产预警处理记录';

CREATE TABLE IF NOT EXISTS `consumable_quality_issue` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `issue_no` varchar(64) NOT NULL COMMENT '问题编号',
  `inventory_id` bigint NOT NULL COMMENT '库存ID',
  `material_id` bigint DEFAULT NULL COMMENT '物资ID',
  `material_code` varchar(64) DEFAULT NULL COMMENT '物资编码',
  `material_name` varchar(128) DEFAULT NULL COMMENT '物资名称',
  `specification` varchar(128) DEFAULT NULL COMMENT '规格',
  `model` varchar(128) DEFAULT NULL COMMENT '型号',
  `registration_number` varchar(128) DEFAULT NULL COMMENT '注册证号',
  `manufacturer` varchar(128) DEFAULT NULL COMMENT '生产厂家',
  `supplier_name` varchar(128) DEFAULT NULL COMMENT '供应商',
  `batch_number` varchar(128) DEFAULT NULL COMMENT '批号',
  `production_date` date DEFAULT NULL COMMENT '生产日期',
  `expiry_date` date DEFAULT NULL COMMENT '有效期',
  `quantity` int NOT NULL COMMENT '问题数量',
  `occurrence_date` datetime NOT NULL COMMENT '发生日期',
  `issue_description` varchar(1000) DEFAULT NULL COMMENT '问题描述',
  `attachment` varchar(255) DEFAULT NULL COMMENT '附件',
  `creator_id` int DEFAULT NULL COMMENT '登记人ID',
  `creator_name` varchar(64) DEFAULT NULL COMMENT '登记人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记 0正常 1删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_quality_issue_no` (`issue_no`),
  KEY `idx_quality_issue_inventory` (`inventory_id`),
  KEY `idx_quality_issue_date` (`occurrence_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='耗材质量问题登记';

CREATE TABLE IF NOT EXISTS `adverse_event_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `event_no` varchar(64) NOT NULL COMMENT '事件编号',
  `patient_name` varchar(64) NOT NULL COMMENT '患者姓名',
  `gender` varchar(16) DEFAULT NULL COMMENT '性别',
  `age` int DEFAULT NULL COMMENT '年龄',
  `patient_id` varchar(64) DEFAULT NULL COMMENT '患者/条码号',
  `hospitalization_no` varchar(64) DEFAULT NULL COMMENT '住院号',
  `involved_project` varchar(255) DEFAULT NULL COMMENT '涉及项目',
  `event_name` varchar(255) NOT NULL COMMENT '事件名称',
  `occurrence_date` datetime NOT NULL COMMENT '发生日期',
  `event_summary` text COMMENT '事件概述',
  `investigation_situation` text COMMENT '调查情况',
  `event_analysis` text COMMENT '事件分析',
  `event_summary_detail` text COMMENT '事件总结',
  `handling_result` text COMMENT '处理结果',
  `rectification_measures` text COMMENT '整改措施',
  `attachment` varchar(255) DEFAULT NULL COMMENT '附件',
  `recorder_id` int DEFAULT NULL COMMENT '登记人ID',
  `recorder_name` varchar(64) DEFAULT NULL COMMENT '登记人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记 0正常 1删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_adverse_event_no` (`event_no`),
  KEY `idx_adverse_event_date` (`occurrence_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医疗器械不良事件登记';